quarkus.application.version=0.0.1

quarkus.container-image.build=true
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=rmdantas12
quarkus.container-image.name=store
quarkus.container-image.tag=${quarkus.application.version}
